/* CORE HANDLER SNAPSHOT — do not edit; generated by SaaS Router v2.0 */
import canonicalize from "canonicalize";
import nacl from "tweetnacl";

const CORS_METHODS = "GET, POST, OPTIONS";
const CORS_HEADERS = "content-type,x-api-key";
function splitCsv(v){ return (v||"").split(",").map(s=>s.trim()).filter(Boolean) }
function allowOrigin(request, env){
  const origin = request.headers.get("origin");
  const allow = splitCsv(env.ALLOWED_ORIGINS||"*");
  if(allow.includes("*") || !origin) return "*";
  return allow.includes(origin) ? origin : "null";
}
function onlyKeys(obj, allowed){ const keys = Object.keys(obj||{}); return !keys.some(k => !allowed.includes(k)) }
function isPlainObject(v){ return !!v && typeof v === "object" && !Array.isArray(v); }
function isSafeMeta(meta){
  if(!isPlainObject(meta)) return false;
  const keys = Object.keys(meta);
  if(keys.length > 128) return false;
  for(const k of keys){
    if(typeof k!=="string" || !k.length || k.length>128) return false;
    const v = meta[k];
    const t = typeof v;
    if(t==="object" || t==="function" || t==="symbol") return false;
    if(t==="number"){
      if(!Number.isFinite(v)) return false;
      if(Object.is(v,-0)) return false;
    }
    if(t==="string" && v.length>4096) return false;
  }
  return true;
}
function b64ToBytes(b64){ const bin=atob(b64); const out=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) out[i]=bin.charCodeAt(i); return out }
function bytesToB64(bytes){ let s=""; for(let i=0;i<bytes.length;i++) s+=String.fromCharCode(bytes[i]); return btoa(s) }
function b64url(bytes){ return bytesToB64(bytes).replace(/=+$/,"").replace(/\+/g,"-").replace(/\//g,"_") }
async function sha256(bytes){ const d=await crypto.subtle.digest("SHA-256", bytes); return new Uint8Array(d) }
function j(obj, status=200, extra={}){ return new Response(JSON.stringify(obj),{status,headers:{
  "content-type":"application/json","access-control-allow-origin":extra["access-control-allow-origin"]??"*",
  "access-control-allow-methods":CORS_METHODS,"access-control-allow-headers":CORS_HEADERS,...extra}}) }
function normRefPath(p){ if(typeof p!=="string"||!p.length) return null; return p.startsWith("/")? p : ("/"+p) }

async function fetchAssetBuf(path, env){
  const url = new URL("https://assets.local"+path);
  const res = await env.ASSETS.fetch(new Request(url,{method:"GET"}));
  if(res.ok) return new Uint8Array(await res.arrayBuffer());
  return null;
}

const REQ_ENV = ["QM_MODE","QM_VERSION","RECURSIVE_LOGIC","C2_POLICY","SYMBOLOGY_MODE","DREAMTIME_MODE"];
function checkInfinity(env){
  const missing = REQ_ENV.filter(k => !env[k] || String(env[k]).trim()==="");
  const modes = {
    quantum_memory: (!!env.QM_MODE && !!env.QM_VERSION) ? "set" : "missing",
    recursive_logic: !!env.RECURSIVE_LOGIC ? "set" : "missing",
    command_control: !!env.C2_POLICY ? "set" : "missing",
    symbology: !!env.SYMBOLOGY_MODE ? "set" : "missing",
    dreamtime: !!env.DREAMTIME_MODE ? "set" : "missing",
  };
  return { ok: missing.length===0, missing, modes };
}

function loadKeys(env){
  const pubB64 = env.ED25519_PUBLIC_B64, secB64 = env.ED25519_SECRET_B64;
  if(!pubB64 || !secB64) return null;
  const pk = b64ToBytes(pubB64), sk = b64ToBytes(secB64);
  if(pk.length!==32 || sk.length!==64) return null;
  return { pk, sk, pubB64 };
}
async function signObject(payloadObj, env){
  const keys = loadKeys(env);
  if(!keys) return { ok:false, error:"sign_keys_missing_or_bad" };
  const canon = canonicalize(payloadObj);
  if(typeof canon!=="string") return { ok:false, error:"canonicalize_failed" };
  const digest = await sha256(new TextEncoder().encode(canon));
  const signature = nacl.sign.detached(digest, keys.sk);
  return { ok:true, payload: payloadObj, sig:{
    alg:"Ed25519-SHA256-RFC8785", publicKey: keys.pubB64, sig: bytesToB64(signature), hash: b64url(digest) } };
}

const MAX_REFS = 1024;
async function verifyRefs(refs, env){
  if(!Array.isArray(refs)) return { ok:false, error:"refs_not_array" };
  if(refs.length>MAX_REFS) return { ok:false, error:"too_many_refs", limit:MAX_REFS };
  for(let i=0;i<refs.length;i++){
    const r=refs[i]||{};
    if(!onlyKeys(r,["path","hash"])) return { ok:false, error:"refs_schema_error", index:i };
    const path = normRefPath(r.path);
    if(!path || typeof r.hash!=="string" || !r.hash.length) return { ok:false, error:"refs_schema_error", index:i };
    if(path.includes("..") || /%2f/i.test(path)) return { ok:false, error:"ref_path_invalid", index:i };
    const buf = await fetchAssetBuf(path, env);
    if(!buf || !(buf instanceof Uint8Array) || buf.length===0) return { ok:false, error:"asset_fetch_failed", index:i };
    const digest = await sha256(buf), got=b64url(digest);
    if(got !== r.hash) return { ok:false, error:"refs_mismatch", index:i, expect:r.hash, got };
  }
  return { ok:true };
}

export default {
  async fetch(request, env){
    if(request.method==="OPTIONS"){
      return new Response(null,{headers:{
        "access-control-allow-origin": allowOrigin(request, env),
        "access-control-allow-methods": CORS_METHODS,
        "access-control-allow-headers": CORS_HEADERS
      }});
    }
    const url = new URL(request.url); const reqId = crypto.randomUUID();

    if(url.pathname==="/health" && request.method==="GET"){
      return j({ ok:true, enabled:true, mode:(env.VERIFY_MODE||"verify") },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"health;dur=0"});
    }

    if(url.pathname==="/infinity" && request.method==="GET"){
      const gate=checkInfinity(env); const strict=(env.INFINITY_GATE==="1"); const status=(strict && !gate.ok)?503:200;
      return j({ ok:gate.ok, zero_entropy:gate.ok, strict_gate:strict, modes:gate.modes, missing:gate.missing, verify_mode:(env.VERIFY_MODE||"verify") },status,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"infinity;dur=0"});
    }

    if(url.pathname==="/policy" && request.method==="POST"){
      const gate=checkInfinity(env); if(env.INFINITY_GATE==="1" && !gate.ok) return j({ok:false,error:"infinity_missing",missing:gate.missing},503,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
      let body; try{ body=await request.json() }catch{ return j({ok:false,error:"invalid_json"},400) }
      if(!onlyKeys(body,["rules","scopes","obligations"])) return j({ok:false,error:"schema_error"},400);
      const canonical=canonicalize({ rules: body.rules||[], scopes: body.scopes||[], obligations: body.obligations||[] });
      const digest=await sha256(new TextEncoder().encode(canonical)); const id=b64url(digest);
      const compiled={ id, nodes:(body.rules||[]).length, scopes:Array.isArray(body.scopes)?body.scopes.length:0, obligations:Array.isArray(body.obligations)?body.obligations.length:0 };
      const signed=await signObject({ policy:{ id, compiled } }, env); if(!signed.ok) return j({ok:false,error:signed.error},503);
      return j({ ok:true, ...signed },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"policy;dur=0"});
    }

    if(url.pathname==="/ground" && request.method==="POST"){
      const gate=checkInfinity(env); if(env.INFINITY_GATE==="1" && !gate.ok) return j({ok:false,error:"infinity_missing",missing:gate.missing},503,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
      let body; try{ body=await request.json() }catch{ return j({ok:false,error:"invalid_json"},400) }
      if(!onlyKeys(body,["query","refs"])) return j({ok:false,error:"schema_error"},400);
      const refsIn=Array.isArray(body.refs)?body.refs:[]; const refsOut=[];
      for(let i=0;i<refsIn.length;i++){ const p=normRefPath(refsIn[i].path); if(!p) return j({ok:false,error:"refs_schema_error",index:i},400);
        const buf=await fetchAssetBuf(p, env); if(!buf) return j({ok:false,error:"asset_fetch_failed",index:i},404);
        const dig=await sha256(buf); refsOut.push({path:p,hash:b64url(dig)}); }
      const signed=await signObject({ ground:{ query:body.query||"", refs:refsOut } }, env); if(!signed.ok) return j({ok:false,error:signed.error},503);
      return j({ ok:true, ...signed },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"ground;dur=0"});
    }

    if(url.pathname==="/playbook" && request.method==="POST"){
      let body; try{ body=await request.json() }catch{ return j({ok:false,error:"invalid_json"},400) }
      if(!onlyKeys(body,["tasks","edges","scope"])) return j({ok:false,error:"schema_error"},400);
      const pb = { tasks:Array.isArray(body.tasks)?body.tasks:[], edges:Array.isArray(body.edges)?body.edges:[], scope: body.scope||"default" };
      const id = b64url(await sha256(new TextEncoder().encode(canonicalize(pb))));
      const signed=await signObject({ playbook:{ id, size:{tasks:pb.tasks.length,edges:pb.edges.length}, scope:pb.scope } }, env);
      if(!signed.ok) return j({ok:false,error:signed.error},503);
      return j({ ok:true, ...signed },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
    }

    if(url.pathname==="/sensor" && request.method==="POST"){
      let body; try{ body=await request.json() }catch{ return j({ok:false,error:"invalid_json"},400) }
      const signed=await signObject({ sensor:{ ts:Date.now(), count:Array.isArray(body)?body.length:1 } }, env);
      if(!signed.ok) return j({ok:false,error:signed.error},503);
      return j({ ok:true, ...signed },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
    }

    if(url.pathname==="/track" && request.method==="GET"){
      const id = new URL(request.url).searchParams.get("id") || "unknown";
      const signed=await signObject({ track:{ id, status:"stub" } }, env);
      if(!signed.ok) return j({ok:false,error:signed.error},503);
      return j({ ok:true, ...signed },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
    }

    if(url.pathname==="/fusion" && request.method==="POST"){
      let body; try{ body=await request.json() }catch{ return j({ok:false,error:"invalid_json"},400) }
      const signed=await signObject({ fusion:{ inputs:Array.isArray(body)?body.length:1, result:"stub" } }, env);
      if(!signed.ok) return j({ok:false,error:signed.error},503);
      return j({ ok:true, ...signed },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
    }

    if(url.pathname==="/verify" && request.method==="POST"){
      if(env.INFINITY_GATE==="1"){ const gate=checkInfinity(env); if(!gate.ok) return j({ok:false,error:"infinity_missing",missing:gate.missing},503,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)}); }
      const apiKey = request.headers.get("x-api-key"); if(!apiKey || (env.VERIFY_API_KEY && apiKey!==env.VERIFY_API_KEY)) return j({ok:false,error:"unauthorized"},401,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env)});
      let body; try{ body=await request.json() }catch{ return j({ok:false,error:"invalid_json"},400,{"x-request-id":reqId}) }
      if(!onlyKeys(body,["meta","refs","sig"])) return j({ok:false,error:"schema_error"},400,{"x-request-id":reqId});
      if(!isPlainObject(body.meta) || !Array.isArray(body.refs) || !isPlainObject(body.sig)) return j({ok:false,error:"schema_error"},400,{"x-request-id":reqId});
      if(!isSafeMeta(body.meta)) return j({ok:false,error:"meta_schema_error"},400,{"x-request-id":reqId});

      const refsCheck=await verifyRefs(body.refs,env);
      if(!refsCheck.ok) return j({ok:false,refs_ok:false,sig_ok:false,error:refsCheck.error,index:refsCheck.index},422,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"refs;dur=0"});

      const sig=body.sig;
      if(!onlyKeys(sig,["alg","publicKey","sig","hash","algorithm","kid"])) return j({ok:false,error:"sig_schema_error"},400,{"x-request-id":reqId});
      if(sig.alg!=="Ed25519-SHA256-RFC8785") return j({ok:false,error:"unsupported_alg"},400,{"x-request-id":reqId});
      if(!sig.publicKey || !sig.sig || !sig.hash) return j({ok:false,error:"schema_error"},400,{"x-request-id":reqId});
      if(!/^[A-Za-z0-9_-]+$/.test(sig.hash)) return j({ok:false,error:"hash_format_error"},400,{"x-request-id":reqId});
      if(env.ED25519_PUBLIC_B64 && sig.publicKey!==env.ED25519_PUBLIC_B64) return j({ok:false,error:"key_mismatch"},400,{"x-request-id":reqId});

      const canonical = canonicalize({ meta: body.meta, refs: body.refs }); if(typeof canonical!=="string" || !canonical.length) return j({ok:false,error:"canonicalize_failed"},400,{"x-request-id":reqId});
      const digest = await sha256(new TextEncoder().encode(canonical)); const digestUrl=b64url(digest);

      if(digestUrl!==sig.hash) return j({ok:false,refs_ok:true,sig_ok:false,error:"hash_mismatch"},422,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"verify;dur=0"});
      let pk,sg; try{ pk=b64ToBytes(sig.publicKey) }catch{ return j({ok:false,error:"bad_public_key"},400,{"x-request-id":reqId}) }
      try{ sg=b64ToBytes(sig.sig) }catch{ return j({ok:false,error:"bad_signature_encoding"},400,{"x-request-id":reqId}) }
      if(pk.length!==32 || sg.length!==64) return j({ok:false,error:"wrong_key_sig_size"},400,{"x-request-id":reqId});
      const sigOk = nacl.sign.detached.verify(digest, sg, pk); if(!sigOk) return j({ok:false,refs_ok:true,sig_ok:false,error:"bad_signature"},422,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"verify;dur=0"});
      return j({ ok:true, refs_ok:true, sig_ok:true, request_id:reqId },200,{"x-request-id":reqId,"access-control-allow-origin":allowOrigin(request,env),"server-timing":"verify;dur=0"});
    }

    return new Response("not found",{status:404,headers:{
      "access-control-allow-origin": allowOrigin(request, env),
      "access-control-allow-methods": CORS_METHODS,
      "access-control-allow-headers": CORS_HEADERS
    }});
  }
};